### ISSUE TITLE
Fleeting "no response data" error.

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [synchrony/smsn#49]
After appearing to run `M-x smsn` successfully, I ran `C-c f` (find all roots), which I expected to be fast because I was starting a fresh graph. I got an error that I've seen before in Emacs: a one-liner about "no response data". I checked the log and it showed this:

```
[WARN] AbstractEvalOpProcessor - Exception processing a script on r
equest [RequestMessage{, requestId=null, op='eval', processor='sess
ion', args={language=smsn, session=undefined, gremlin={"action":"ne
t.fortytwo.smsn.server.actions.FindRoots","height":1,"filter":{"min
Source":null,"defaultSource":null,"minWeight":0.0,"defaultWeight":0
.5},"titleCutoff":100,"style":"forward"}}}]. 
java.lang.NullPointerException 
       at com.google.common.base.Preconditions.checkNotNull(Precon
ditions.java:210) 
       at net.fortytwo.smsn.brain.model.Filter.indexForSource(Filt
er.java:69) 
       at net.fortytwo.smsn.brain.model.Filter.setMinSource(Filter
.java:60) 
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Meth
od) 
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethod
AccessorImpl.java:62) 
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Delegati
ngMethodAccessorImpl.java:43) 
       at java.lang.reflect.Method.invoke(Method.java:498) 
       at org.apache.tinkerpop.shaded.jackson.databind.deser.impl.
MethodProperty.deserializeAndSet(MethodProperty.java:97) 
       at org.apache.tinkerpop.shaded.jackson.databind.deser.BeanD
eserializer.vanillaDeserialize(BeanDeserializer.java:260) 
       at org.apache.tinkerpop.shaded.jackson.databind.deser.BeanD
eserializer.deserialize(BeanDeserializer.java:125) 
       at org.apache.tinkerpop.shaded.jackson.databind.deser.Setta
bleBeanProperty.deserialize(SettableBeanProperty.java:490) 
       at org.apache.tinkerpop.shaded.jackson.databind.deser.impl.
MethodProperty.deserializeAndSet(MethodProperty.java:95) 
       at org.apache.tinkerpop.shaded.jackson.databind.deser.BeanD
eserializer.vanillaDeserialize(BeanDeserializer.java:260) 
       at org.apache.tinkerpop.shaded.jackson.databind.deser.BeanD
eserializer._deserializeOther(BeanDeserializer.java:163) 
       at org.apache.tinkerpop.shaded.jackson.databind.deser.BeanD
eserializer.deserialize(BeanDeserializer.java:135) 
       at org.apache.tinkerpop.shaded.jackson.databind.jsontype.im
pl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyType
Deserializer.java:120) 
       at org.apache.tinkerpop.shaded.jackson.databind.jsontype.im
pl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsProperty
TypeDeserializer.java:91) 
       at org.apache.tinkerpop.shaded.jackson.databind.deser.Abstr
actDeserializer.deserializeWithType(AbstractDeserializer.java:142) 
       at org.apache.tinkerpop.shaded.jackson.databind.deser.impl.
TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:42
) 
       at org.apache.tinkerpop.shaded.jackson.databind.ObjectMappe
r._readMapAndClose(ObjectMapper.java:3789) 
       at org.apache.tinkerpop.shaded.jackson.databind.ObjectMappe
r.readValue(ObjectMapper.java:2779) 
       at net.fortytwo.smsn.server.SmSnScriptEngine.readAsJson(SmS
nScriptEngine.java:61) 
       at net.fortytwo.smsn.server.SmSnScriptEngine.deserializeReq
uest(SmSnScriptEngine.java:133) 
       at net.fortytwo.smsn.server.SmSnScriptEngine.handleRequest(
SmSnScriptEngine.java:120) 
       at net.fortytwo.smsn.server.SmSnScriptEngine.eval(SmSnScrip
tEngine.java:42) 
       at javax.script.AbstractScriptEngine.eval(AbstractScriptEng
ine.java:233) 
       at org.apache.tinkerpop.gremlin.groovy.engine.ScriptEngines
.eval(ScriptEngines.java:120) 
       at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecut
or.lambda$eval$2(GremlinExecutor.java:314) 
       at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
       at java.util.concurrent.ThreadPoolExecutor.runWorker(Thread
PoolExecutor.java:1142) 
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(Threa
dPoolExecutor.java:617) 
       at java.lang.Thread.run(Thread.java:748) 
INFO: Fri Jun 16 00:46:15 UTC 2017: net.fortytwo.smsn.server.Action
handleRequest: completed GetConfiguration action in 33 ms
```

After restarting emacs (leaving smsn running) I couldn't reproduce the error.

**Comment by joshsh** [comment]
I have added a more informative error message for this error condition (in which a specified data source does not exist).  Checked in to develop.  If you rebuild and redeploy, you will have more information if this happens again.

**Comment by JeffreyBenjaminBrown** [comment]
Roger! Built, deployed, pushed to DockerHub.

**Comment by joshsh** [comment]
Great.  We do need error messages to propagate better into Emacs, but I will save that for a separate issue.

**Comment by joshsh** [comment]
https://github.com/synchrony/smsn-mode/issues/24
