### ISSUE TITLE
mvn clean install -- fails

### ISSUE THREAD

**Issue by gnusupport** [synchrony/smsn#62]
```
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/home/data1/protected/Programming/git/smsn). Please verify you invoked Maven from the correct directory. -> [Help 1]
org.apache.maven.lifecycle.MissingProjectException: The goal you specified requires a project to execute but there is no POM in this directory (/home/data1/protected/Programming/git/smsn). Please verify you invoked Maven from the correct directory.
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:84)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by jmatsushita** [comment]
I also ran into the same issue, and had to use `gradle shadowJar` since the project [has migrated to gradle](https://github.com/synchrony/smsn/commit/636ddb17c122da57e845ed2b831e3cdeabdb82db).

**Comment by joshsh** [comment]
I feel like I'm missing something. Why would you try to build the project using Maven? It is meant to be built with the provided `gradlew` script.

**Comment by joshsh** [comment]
Closing (to test Discord webhook). Feel free to reopen if this is still an issue.
